version: '3.9'

services:
  api:
    build: ./packages/api
    container_name: shortlink_api
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/shortlinks
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortlinks
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  pgdata:
