version: "3.7"

services:
  api:
    build: .
    container_name: shortlink_api
    ports:
      - "8080:3000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/shortlinks
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortlinks
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

volumes:
  pgdata:
