openapi: 3.1.0
info:
  title: 🚀 API de Shortlink
  version: 1.0.0
  description: |
    API para encurtar URLs, gerar slugs únicos e redirecionar para a URL original.  
    Ideal para criar encurtadores personalizados e monitorar tráfego.

tags:
  - name: Shortlink
    description: Endpoints para encurtar URLs e redirecionar usando slugs.

paths:
  /shorten:
    post:
      summary: Encurtar uma URL
      description: Recebe uma URL válida e retorna um link encurtado.
      tags:
        - Shortlink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenRequest'
            examples:
              exemplo1:
                summary: Encurtando uma URL simples
                value:
                  url: https://example.com/produto/123
      responses:
        '200':
          description: URL encurtada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
              examples:
                sucesso:
                  summary: Retorno do encurtador
                  value:
                    shortlink: https://meusite.com/abc123
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno no servidor

  /{slug}:
    get:
      summary: Redirecionar para a URL original
      description: Retorna redirecionamento **302** para a URL encurtada.
      tags:
        - Shortlink
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
          description: Slug da URL encurtada.
      responses:
        '302':
          description: Redirecionamento para a URL original
          headers:
            Location:
              description: URL original
              schema:
                type: string
        '404':
          description: Slug não encontrado
        '500':
          description: Erro interno no servidor

components:
  schemas:
    ShortenRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          example: https://example.com/alguma-pagina

    ShortenResponse:
      type: object
      properties:
        shortlink:
          type: string
          example: https://meusite.com/abc123

x-theme:
  sidebar: dark
  colors:
    primary: "#6d5eb6"
    background: "#121212"
    text: "#e0e0e0"
    response:
      success: "#4caf50"
      error: "#f44336"
