openapi: 3.1.0
info:
  title: API de Shortlink
  version: 1.0.0
  description: API para encurtar URLs e redirecionar usando slugs

paths:
  /shorten:
    post:
      summary: Encurta uma URL
      tags:
        - Shortlink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenRequest'
      responses:
        '200':
          description: URL encurtada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenResponse'
        '400':
          description: Requisição inválida

  /{slug}:
    get:
      summary: Redireciona para a URL original
      tags:
        - Shortlink
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
          description: Slug da URL encurtada
      responses:
        '302':
          description: Redirecionamento para a URL original
          headers:
            Location:
              description: URL original
              schema:
                type: string
        '404':
          description: Slug não encontrado

components:
  schemas:
    ShortenRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          example: https://example.com/alguma-pagina

    ShortenResponse:
      type: object
      properties:
        shortlink:
          type: string
          example: http://localhost:3000/abc123
